copyright = "Â© 2024 - Romy Odoni"
baseURL = 'https://https://romy-odoni-art.netlify.app'
languageCode = 'en-us'
title = 'Rodoni Art'
theme = 'gallery'
[params]
  defaultTheme = 'light'
  [params.author]
    name = "Romy Odoni"
  [params.socialIcons]
    email = "mailto:user@example.com"
    whatsapp = "https://wa.me/+41789625847"
