copyright = "© 2025 - Romy Odoni"
baseURL = 'https://romy-odoni-art.netlify.app'
languageCode = 'en-us'
title = ''
theme = 'gallery'
[params]
  defaultTheme = 'light'
  footerText = "Kontaktieren Sie mich, um mehr über die Bilder und die Preise zu erfahren" 
  [params.author]
    name = "Romy Odoni"
  [params.socialIcons]
    email = "mailto:romy.odoni@outlook.com"
    instagram = "https://www.instagram.com/rodoni.quadri"
